// Common bird species of Switzerland.
// sci: scientific name (used to fetch photos & sounds), en/fr: display names.
const BIRDS = [
  { sci: "Passer domesticus", en: "House Sparrow", fr: "Moineau domestique" },
  { sci: "Turdus merula", en: "Common Blackbird", fr: "Merle noir" },
  { sci: "Parus major", en: "Great Tit", fr: "Mésange charbonnière" },
  { sci: "Cyanistes caeruleus", en: "Eurasian Blue Tit", fr: "Mésange bleue" },
  { sci: "Periparus ater", en: "Coal Tit", fr: "Mésange noire" },
  { sci: "Aegithalos caudatus", en: "Long-tailed Tit", fr: "Mésange à longue queue" },
  { sci: "Fringilla coelebs", en: "Common Chaffinch", fr: "Pinson des arbres" },
  { sci: "Erithacus rubecula", en: "European Robin", fr: "Rougegorge familier" },
  { sci: "Troglodytes troglodytes", en: "Eurasian Wren", fr: "Troglodyte mignon" },
  { sci: "Sturnus vulgaris", en: "Common Starling", fr: "Étourneau sansonnet" },
  { sci: "Corvus corone", en: "Carrion Crow", fr: "Corneille noire" },
  { sci: "Corvus corax", en: "Common Raven", fr: "Grand Corbeau" },
  { sci: "Pica pica", en: "Eurasian Magpie", fr: "Pie bavarde" },
  { sci: "Garrulus glandarius", en: "Eurasian Jay", fr: "Geai des chênes" },
  { sci: "Pyrrhocorax graculus", en: "Alpine Chough", fr: "Chocard à bec jaune" },
  { sci: "Columba palumbus", en: "Common Wood Pigeon", fr: "Pigeon ramier" },
  { sci: "Streptopelia decaocto", en: "Eurasian Collared Dove", fr: "Tourterelle turque" },
  { sci: "Apus apus", en: "Common Swift", fr: "Martinet noir" },
  { sci: "Hirundo rustica", en: "Barn Swallow", fr: "Hirondelle rustique" },
  { sci: "Delichon urbicum", en: "Common House Martin", fr: "Hirondelle de fenêtre" },
  { sci: "Motacilla alba", en: "White Wagtail", fr: "Bergeronnette grise" },
  { sci: "Phoenicurus ochruros", en: "Black Redstart", fr: "Rougequeue noir" },
  { sci: "Turdus philomelos", en: "Song Thrush", fr: "Grive musicienne" },
  { sci: "Sylvia atricapilla", en: "Eurasian Blackcap", fr: "Fauvette à tête noire" },
  { sci: "Phylloscopus collybita", en: "Common Chiffchaff", fr: "Pouillot véloce" },
  { sci: "Prunella modularis", en: "Dunnock", fr: "Accenteur mouchet" },
  { sci: "Chloris chloris", en: "European Greenfinch", fr: "Verdier d'Europe" },
  { sci: "Carduelis carduelis", en: "European Goldfinch", fr: "Chardonneret élégant" },
  { sci: "Pyrrhula pyrrhula", en: "Eurasian Bullfinch", fr: "Bouvreuil pivoine" },
  { sci: "Serinus serinus", en: "European Serin", fr: "Serin cini" },
  { sci: "Sitta europaea", en: "Eurasian Nuthatch", fr: "Sittelle torchepot" },
  { sci: "Dendrocopos major", en: "Great Spotted Woodpecker", fr: "Pic épeiche" },
  { sci: "Picus viridis", en: "European Green Woodpecker", fr: "Pic vert" },
  { sci: "Buteo buteo", en: "Common Buzzard", fr: "Buse variable" },
  { sci: "Milvus milvus", en: "Red Kite", fr: "Milan royal" },
  { sci: "Falco tinnunculus", en: "Common Kestrel", fr: "Faucon crécerelle" },
  { sci: "Anas platyrhynchos", en: "Mallard", fr: "Canard colvert" },
  { sci: "Cygnus olor", en: "Mute Swan", fr: "Cygne tuberculé" },
  { sci: "Ardea cinerea", en: "Grey Heron", fr: "Héron cendré" },
  { sci: "Fulica atra", en: "Eurasian Coot", fr: "Foulque macroule" },
  { sci: "Podiceps cristatus", en: "Great Crested Grebe", fr: "Grèbe huppé" },
  { sci: "Chroicocephalus ridibundus", en: "Black-headed Gull", fr: "Mouette rieuse" },
  { sci: "Alcedo atthis", en: "Common Kingfisher", fr: "Martin-pêcheur d'Europe" },
  { sci: "Cuculus canorus", en: "Common Cuckoo", fr: "Coucou gris" },
  { sci: "Strix aluco", en: "Tawny Owl", fr: "Chouette hulotte" },
];
